[package]
name = "api-util"
version = "0.1.0"
edition = "2024"

[[example]]
name = "query_builder_usage"
path = "../examples/query_builder_usage.rs"

[[example]]
name = "paginator_usage"
path = "../examples/paginator_usage.rs"

[dependencies]
sqlx.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
api-entity = { path = "../api-entity" }
